// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Supershop.Data;

#nullable disable

namespace Supershop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240330165148_recheck1")]
    partial class recheck1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Supershop.Models.items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 0,
                            Name = "Pepsi",
                            Type = "Softdrinks",
                            location = "A1"
                        },
                        new
                        {
                            Id = 2,
                            Count = 0,
                            Name = "Fanta",
                            Type = "Softdrinks",
                            location = "A1"
                        },
                        new
                        {
                            Id = 3,
                            Count = 0,
                            Name = "7up",
                            Type = "Softdrinks",
                            location = "A1"
                        },
                        new
                        {
                            Id = 4,
                            Count = 0,
                            Name = "Cockacola",
                            Type = "Softdrinks",
                            location = "A1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
